configuration: Release

version: 1.0.{build}
branches:
  only:
  - develop
build_script:
- ps: "# Clean up build and pbo folders\nGet-ChildItem -Path ..\\build -Include *.* -File -Recurse -Exclude @(\"README.md\") | foreach { $_.Delete()}\nGet-ChildItem -Path ..\\pbo -Include *.* -File -Recurse -Exclude @(\"builds.txt\") | foreach { $_.Delete()}\n\n# Make the build directory with only valid files from branch\n$from = '..\\'\n$to = '..\\build'\n\nGet-ChildItem -Path $from | % { \n  Copy-Item $_.fullname \"$to\" -Recurse -Force -Exclude @(\"build\",\"pbo\",\"tools\", \"A3M PMC Sandbox.docx\",\".gitattributes\") \n}\n\n# Create the pbo file from the build directory\nmakepbo -NUP ..\\build .\\pbo\\a3m-pmc-simulator.pbo"
test: off
deploy: off
notifications:
- provider: Email
  to:
  - cgunn@whiteshield-inc.com
  subject: Build from A3M-PMC-Simulator
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false

environment:
  access_token:
    secure: 3e32d1ee4d500bba6a0e5239a11545e6419ba963

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git commit ...
  - git push ...
